name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: jq ".messages[0].content = \"$(cat prompt.md)\"" request_template.json > request.json
      - run: >
          curl -s https://api.openai.com/v1/chat/completions
          -H "Content-Type: application/json"
          -H "Authorization: Bearer ${{ secrets.OPEN_AI_KEY }}"
          -d @request.json | tee output.json | jq -r '.choices[0].message.content' > output.md
      - run: echo output.json
      - run: echo output.md
      - run: npm install -g bats
      - run: bats -v
